# Generated by Django 5.0.3 on 2024-04-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0003_palabracompartida_datoscompartidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabracompartida',
            name='total_grupos',
            field=models.IntegerField(default=0),
        ),
    ]
