# Generated by Django 5.0.3 on 2024-04-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0004_palabracompartida_total_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCodeMX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('pais', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
