# Generated by Django 5.0.3 on 2024-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0005_areacodemx_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacodemx',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='countrycode',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
