# Generated by Django 4.2.11 on 2024-04-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0007_palabracompartida_nombre_alter_palabracompartida_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palabracompartida',
            name='nombre',
        ),
    ]
