# Generated by Django 4.2.11 on 2024-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0008_remove_palabracompartida_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabracompartida',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
