# Generated by Django 4.2.11 on 2024-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0009_palabracompartida_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palabracompartida',
            name='nombre',
        ),
        migrations.AddField(
            model_name='palabracompartida',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
