# Generated by Django 4.2.11 on 2024-04-26 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0010_remove_palabracompartida_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabracompartida',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='palabracompartida',
            name='total_grupos',
            field=models.IntegerField(default=0),
        ),
    ]
