# Generated by Django 4.2.11 on 2024-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palabras_admin', '0011_alter_palabracompartida_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabracompartida',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='palabracompartida',
            name='total_grupos',
            field=models.IntegerField(),
        ),
    ]
